[package]
name = "dacquiri"
version = "0.2.0"
edition = "2021"
authors = ["d0nut <d0nut@resync.gg>"]
description = "A compile-time enforcing DAC authorization library."
repository = "https://github.com/resyncgg/dacquiri"
license = "MIT"
readme = "README.md"
homepage = "https://resync.gg"
keywords = ["authorization", "dac", "access", "authz", "security"]
categories = ["authentication"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

include = [
    "Cargo.toml",
    "src/**/*",
    "LICENSE",
]

[features]
default = ["derive"]
derive = ["dacquiri_derive"]

[dependencies]
thiserror = "1"
dacquiri_derive = { version = "0.1.0", optional = true, path = "../dacquiri_derive" }

[dev-dependencies]
trybuild = "1"
dacquiri_derive = { path = "../dacquiri_derive" }

[[example]]
name = "simple"

